export CUDA_VISIBLE_DEVICES=2
export CUDA_LAUNCH_BLOCKING=1
#MODEL="pythia410m"
MODEL="qwen18"
#DATASET="ultrafb"
DATASET="hh"
SFT_EPOCHS=2
N_EPOCHS=16
N_EXAMPLES=80000
EVAL_EVERY=100000
DATE=$(date +%m%d)
python -u train.py \
    loss=masked_dpo \
    loss.beta=0.1 \
    datasets=$DATASET \
    model=$MODEL \
    exp_name="dpo_no_normal_masked_${MODEL}_${DATASET}_ep${N_EPOCHS}_${DATE}-2"\
    trainer=BasicTrainer \
    n_epochs=$N_EPOCHS \
    n_examples=$N_EXAMPLES \
    model.archive="sft_${MODEL}_${DATASET}_ep${SFT_EPOCHS}_1202" \
    save_ckp=true \
    eval_every=$EVAL_EVERY
