export CUDA_VISIBLE_DEVICES=3
export CUDA_LAUNCH_BLOCKING=1
#MODEL="pythia410m"
MODEL="qwen18"
#DATASET="ultrafb"
DATASET="hh"
SFT_EPOCHS=1
N_EPOCHS=6
N_EXAMPLES=30000
EVAL_EVERY=100000
DATE=$(date +%m%d)
python -u train.py \
    loss=dpo \
    loss.beta=0.1 \
    model=$MODEL \
    datasets=$DATASET \
    exp_name="dpo_extend_${MODEL}_${DATASET}_ep${N_EPOCHS}_${DATE}"\
    trainer=BasicTrainer \
    n_epochs=$N_EPOCHS \
    n_examples=$N_EXAMPLES \
    model.archive="extend_sft_${MODEL}_${DATASET}_ep${SFT_EPOCHS}_1202" \
    save_ckp=true \
    eval_every=$EVAL_EVERY
