export CUDA_VISIBLE_DEVICES=2
MODEL="qwen18"
#MODEL="pythia410m"
DATASET="hh"
#DATASET="ultrafb"
TRAINER="BasicTrainer"
TRAIN_SPLIT="train_dpo"
N_EPOCHS=2
N_EXAMPLES=10000
EVAL_EVERY=500
DATE=$(date +%m%d)
python -u train.py \
  model=$MODEL \
  exp_name="sft_${MODEL}_${DATASET}_ep${N_EPOCHS}_${DATE}" \
  datasets=$DATASET \
  trainer="BasicTrainer" \
  train_split="train_dpo" \
  n_epochs=$N_EPOCHS \
  n_examples=$N_EXAMPLES \
  save_ckp="true" \
  eval_every=$EVAL_EVERY
